language: java

jdk:
  - oraclejdk8

install:
  - mvn -f qsearch-querydsl/pom.xml clean install -DskipTests=true

after_success:
  - mvn coveralls:report

script:
  - echo "build finishing"

cache:
  directories:
    - $HOME/.m2